spring:
  application:
    name: PersonalizedDailyReportBot

#  config:
#    import: optional:file:./secrets.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/daily_report_bot_db
    username: postgres
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



server:
  port: 9999

api:
  key:
    telegram: token